== Lessons from RoboSub 2025
Cyclone RoboSub competed for the first time in RoboSub 2026, where we encountered a variety of both challenges and successes that have shaped our testing strategy and methodologies for 2026. The pervasive theme across our technical challenges was untested systems. Our team only received a DVL (graciously loaned by Nortek) one month before the competition. We had previously been solely relying on an IMU for navigation which presented its own set up issues and the addition of a DVL would allow for more reliable navigation. However, the short integration window meant that many of our software and electrical systems were only seriously tested for the first time during the competition week.

During that week we faced physical issues such as faulty ESC connections and kill switch accessibility, and more pervasively, software issues tied to an untested Simulink controller and mission planning system. This combination of unknowns made troubleshooting extremely challenging, especially under the pressure of competition. One thing was abundantly clear, we needed to make real-condition testing the driver of our development process. As a new team, the fastest way we could close the experience gap would be testing and failing as fast as possible during the year to ensure reliability come next July. 

This year we've implemented a simple, yet rigorous weekly testing cycle which is thoroughly detailed in {some appendix section}. This means that each week, we our subteams are expected to have all systems up and running so that we can run software in the real world setting of a pool. These tests have both provided weekly deadlines and exposed characteristics of our system which would otherwise go unnoticed. 


//Our first conversations regarding competition strategy began with the team’s founding in 2023. As a new team, we understood the importance of setting achievable goals, so we set out to cultivate a solid understanding of the competition challenges to inform our team’s expected abilities.

//Our first team meeting involved breaking down the 2023 Team Handbook @handbook and assessing strategy. We cataloged the maximum available points associated with each task, along with the number of teams able to successfully attempt each task as seen in @taskbreakdown. We measured success rate as a team's ability to achieve the maximum points possible within a given task. Furthermore, we gave extra weight to tasks that succinctly demonstrated intended vehicle functionality. Doing so allowed us to identify trends and pinpoint tasks that yielded the most points while falling within most teams’ predicted abilities. 

//During our analysis, we noted that the majority of teams’ points were earned by completing navigation-based tasks such as surfacing in the _Octagon_ and passing through the _Gate_. When compared with precise manipulation tasks, we found that successful attempts were less common. Based on this research, we prioritized navigation-based tasks while de-prioritizing manipulation-based.

//Originally, Cyclone RoboSub planned on competing in the 2024 RoboSub Competition. However, after lengthy deliberation, we chose to postpone competing until 2025 with the intent to use the extra time to build a solid foundation for our vehicle and team. Despite this, we sent representatives to the 2024 RoboSub competition to ask questions and witness different strategies firsthand. During their time at the venue, our representatives spoke with other teams and took detailed notes on the pitfalls and effective strategies teams encountered. Most teams advised against relying on vision systems as a primary means of navigation and instead recommended the use of a Doppler Velocity Log (DVL). Testing early and often was a common theme along with the use of fail-safes spread across all systems.

//This new intel, combined with our previous year’s assessment, culminated in our current competition strategy for the 2025 RoboSub Competition.

== 2025 Competition Strategy
For the 2025 RoboSub Competition, we chose to focus on navigation-based tasks that only required maneuverability. This was based on a previous analysis we conducted which evaluated the types of tasks teams had been successful with at past competitions {appendix reference}.
- *Begin Assessment (Gate):* Manny begins each run with a coinflip, then turns to face the gate
//So, moving forward, we would design an AUV that is nimble and consistent, focusing on navigational tasks. Our research regarding competition strategy formed the core of our design strategy -- it continually informed the decisions we made and philosophies we stood by. Based on the goals we determined achievable, we designed our robot to emphasize successfully completing those tasks. 

// To complement extensive competition research, the most significant competition preparation is the fast-paced hardware testing schedule our team applied bi-weekly. Despite our consistent testing, the principal challenge that we expect to face at the competition is adapting our controller’s navigation strategy to the competition layout. The need for in situational modification and serviceability drove the majority of our design decisions detailed in the following section.