== 2023-2024 Competition Year
Our first conversations regarding competition strategy began with the team’s founding in 2023. As a new team, we understood the importance of setting achievable goals, so we set out to cultivate a solid understanding of the competition challenges to inform our team’s expected abilities.

Our first team meeting involved breaking down the 2023 Team Handbook @handbook and assessing strategy. We cataloged the maximum available points associated with each task, along with the number of teams able to successfully attempt each task as seen in @taskbreakdown. We measured success rate as a team's ability to achieve the maximum points possible within a given task. Furthermore, we gave extra weight to tasks that succinctly demonstrated intended vehicle functionality. Doing so allowed us to identify trends and pinpoint tasks that yielded the most points while falling within most teams’ predicted abilities. 

During our analysis, we noted that the majority of teams’ points were earned by completing navigation-based tasks such as surfacing in the _Octagon_ and passing through the _Gate_. When compared with precise manipulation tasks, we found that successful attempts were less common. Based on this research, we prioritized navigation-based tasks while de-prioritizing manipulation-based.

Originally, Cyclone RoboSub planned on competing in the 2024 RoboSub Competition. However, after lengthy deliberation, we chose to postpone competing until 2025 with the intent to use the extra time to build a solid foundation for our vehicle and team. Despite this, we sent representatives to the 2024 RoboSub competition to ask questions and witness different strategies firsthand. During their time at the venue, our representatives spoke with other teams and took detailed notes on the pitfalls and effective strategies teams encountered. Most teams advised against relying on vision systems as a primary means of navigation and instead recommended the use of a Doppler Velocity Log (DVL). Testing early and often was a common theme along with the use of fail-safes spread across all systems.

This new intel, combined with our previous year’s assessment, culminated in our current competition strategy for the 2025 RoboSub Competition.

== 2025 Competition Strategy
For the 2025 RoboSub Competition, we chose to prioritize the _Gate_, _Octagon_, and _Bin_ tasks with a plan to add functionality for the _Return Home_ and _Coinflip_ tasks with time permitting. Manatee was designed to be small and maneuverable, allowing it to accumulate style points by rolling as it passed through the gate. The vehicle primarily relies on its DVL from Nortek @dvl, and Inertial Measurement Unit (IMU) from InertialSense @imu, to navigate the pool. 

To facilitate less complex vision-based tasks, Manatee is equipped with two cameras, one forward-facing and one downward-facing. The forward-facing camera recognizes which side of the _Gate_ the vehicle passes through at the start of the run to inform our dropper location at the _Bin_ task. The downward-facing camera allows Manatee to accurately position itself above the correct side of the _Bin_ before releasing both droppers in succession.

Beyond the dropper, our design focus centered around keeping the vehicle small and nimble enabling it to efficiently complete navigation-based tasks such as the _Gate_ and _Octagon_. This research regarding competition strategy formed the basis of our design strategy.
//So, moving forward, we would design an AUV that is nimble and consistent, focusing on navigational tasks. Our research regarding competition strategy formed the core of our design strategy -- it continually informed the decisions we made and philosophies we stood by. Based on the goals we determined achievable, we designed our robot to emphasize successfully completing those tasks. 

// To complement extensive competition research, the most significant competition preparation is the fast-paced hardware testing schedule our team applied bi-weekly. Despite our consistent testing, the principal challenge that we expect to face at the competition is adapting our controller’s navigation strategy to the competition layout. The need for in situational modification and serviceability drove the majority of our design decisions detailed in the following section.